// Mocks generated by Mockito 5.4.4 from annotations
// in diet_macro/test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:diet_macro/core/network/oauth1.0/oauth_helper.dart' as _i2;
import 'package:diet_macro/data/datasource/local/isar_datasource.dart' as _i3;
import 'package:diet_macro/data/datasource/remote/food_search_api.dart' as _i6;
import 'package:diet_macro/data/isar/isar_data.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOAuthHelper_0 extends _i1.SmartFake implements _i2.OAuthHelper {
  _FakeOAuthHelper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IsarDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsarDatasource extends _i1.Mock implements _i3.IsarDatasource {
  @override
  _i4.Future<List<_i5.MealData>> getMealsByDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealsByDate,
          [date],
        ),
        returnValue: _i4.Future<List<_i5.MealData>>.value(<_i5.MealData>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.MealData>>.value(<_i5.MealData>[]),
      ) as _i4.Future<List<_i5.MealData>>);

  @override
  _i4.Future<void> addMealData(_i5.MealData? mealData) => (super.noSuchMethod(
        Invocation.method(
          #addMealData,
          [mealData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.DailyData?> getDailyDataByDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyDataByDate,
          [date],
        ),
        returnValue: _i4.Future<_i5.DailyData?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.DailyData?>.value(),
      ) as _i4.Future<_i5.DailyData?>);

  @override
  _i4.Future<_i5.TargetData?> getTargetData() => (super.noSuchMethod(
        Invocation.method(
          #getTargetData,
          [],
        ),
        returnValue: _i4.Future<_i5.TargetData?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.TargetData?>.value(),
      ) as _i4.Future<_i5.TargetData?>);

  @override
  _i4.Future<void> updateDailyData(_i5.DailyData? dailyData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDailyData,
          [dailyData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTargetData(_i5.TargetData? targetData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTargetData,
          [targetData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllDailyData() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllDailyData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTargetData(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTargetData,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [FoodSearchApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodSearchApi extends _i1.Mock implements _i6.FoodSearchApi {
  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i2.OAuthHelper get oAuthHelper => (super.noSuchMethod(
        Invocation.getter(#oAuthHelper),
        returnValue: _FakeOAuthHelper_0(
          this,
          Invocation.getter(#oAuthHelper),
        ),
        returnValueForMissingStub: _FakeOAuthHelper_0(
          this,
          Invocation.getter(#oAuthHelper),
        ),
      ) as _i2.OAuthHelper);

  @override
  _i4.Future<String> fetchFoodNutrition(String? foodName) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchFoodNutrition,
          [foodName],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #fetchFoodNutrition,
            [foodName],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #fetchFoodNutrition,
            [foodName],
          ),
        )),
      ) as _i4.Future<String>);
}
